### ISSUE TITLE
show/hide config area

### ISSUE THREAD

**Issue by dai-shi** [dai-shi/remote-faces#36]
something like this:

<img width="606" alt="2020-04-17 12 20 00" src="https://user-images.githubusercontent.com/490574/79528981-6f646b80-80a6-11ea-8f68-b9e3739101f8.png">

**Comment by kobatastu** [comment]
I propose show/hide config button in #41

**Comment by dai-shi** [comment]
#41 is merged, but let's keep this issue open because we can still make the UI compact by putting the button in the status line.

**Comment by dai-shi** [comment]
It would also be nice to store show/hide state in localStorage, so that it will be kept hidden upon reload.
